from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingMultiStepFeedback,
    QgsProcessingParameterEnum,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterFile,
    QgsProcessingParameterDefinition,
    QgsProcessingContext,
)
import processing
import csv


class CreateCsvs(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterEnum(
                "LandCoverType",
                "Land Cover Type",
                options=["NLCD", "CCAP"],
                allowMultiple=False,
                defaultValue=0,
            )
        )
        self.addParameter(
            QgsProcessingParameterFile(
                "OutputCSV",
                "Output CSV",
                behavior=QgsProcessingParameterFile.File,
                fileFilter="CSV Files (*.csv)",
                defaultValue=None,
            )
        )
        self.addParameter(
            QgsProcessingParameterBoolean(
                "OpenOutputFile",
                "Open output file after running algorithm",
                defaultValue=True,
            )
        )

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(0, model_feedback)
        results = {}
        outputs = {}

        # Find the template based on the land cover values chosen
        land_cover = self.parameterAsInt(parameters, "LandCoverType", context)
        if land_cover == 0:
            template = self.ncld_properties()
            layer_name = "NCLD"
        elif land_cover == 1:
            template = self.ccap_properties()
            layer_name = "CCAP"
        template.sort(key=lambda lc: lc["lu_value"])

        csv_path = self.parameterAsString(parameters, "OutputCSV", context)
        fieldnames = [
            "lu_value",
            "lu_name",
            "cn_a",
            "cn_b",
            "cn_c",
            "cn_d",
            "c_factor",
            "tss",
            "lead",
            "zinc",
            "nitrogen",
            "phosphorus",
        ]
        with open(csv_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for properties in template:
                writer.writerow(properties)
        outputs["CSV"] = csv_path

        add_layer = self.parameterAsBool(parameters, "OpenOutputFile", context)
        if add_layer:
            context.addLayerToLoadOnCompletion(
                csv_path,
                QgsProcessingContext.LayerDetails(
                    layer_name, context.project(), layer_name
                ),
            )

        return results

    def name(self):
        return "Create CSVs"

    def displayName(self):
        return "Create CSVs"

    def group(self):
        return ""

    def groupId(self):
        return ""

    def createInstance(self):
        return CreateCsvs()

    def ncld_properties(self):
        return [
            {
                "lu_value": 11,
                "lu_name": "Water",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 12,
                "lu_name": "Perennial Ice / Snow",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 100,
                "zinc": 0,
            },
            {
                "lu_value": 21,
                "lu_name": "Developed Open Space",
                "cn_a": 0.49,
                "cn_b": 0.69,
                "cn_c": 0.79,
                "cn_d": 0.84,
                "c_factor": 0.005,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0.03,
            },
            {
                "lu_value": 22,
                "lu_name": "Low Intensity Developed",
                "cn_a": 0.61,
                "cn_b": 0.75,
                "cn_c": 0.83,
                "cn_d": 0.87,
                "c_factor": 0.03,
                "lead": 0.06,
                "nitrogen": 1.77,
                "phosphorus": 0.18,
                "tss": 19.1,
                "zinc": 0.06,
            },
            {
                "lu_value": 23,
                "lu_name": "Medium Intensity Developed",
                "cn_a": 0.77,
                "cn_b": 0.85,
                "cn_c": 0.9,
                "cn_d": 0.92,
                "c_factor": 0.01,
                "lead": 0,
                "nitrogen": 1.25,
                "phosphorus": 0.48,
                "tss": 55.3,
                "zinc": 0.08,
            },
            {
                "lu_value": 24,
                "lu_name": "High Intensity Developed",
                "cn_a": 0.89,
                "cn_b": 0.92,
                "cn_c": 0.94,
                "cn_d": 0.95,
                "c_factor": 0,
                "lead": 0.09,
                "nitrogen": 2.22,
                "phosphorus": 0.47,
                "tss": 71,
                "zinc": 0.09,
            },
            {
                "lu_value": 31,
                "lu_name": "Bare Land",
                "cn_a": 0.77,
                "cn_b": 0.86,
                "cn_c": 0.91,
                "cn_d": 0.94,
                "c_factor": 0.7,
                "lead": 0.03,
                "nitrogen": 0.97,
                "phosphorus": 0.12,
                "tss": 70,
                "zinc": 0.03,
            },
            {
                "lu_value": 41,
                "lu_name": "Deciduous Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.009,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 42,
                "lu_name": "Evergreen Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.004,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 43,
                "lu_name": "Mixed Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.007,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 51,
                "lu_name": "Dwarf Shrub",
                "cn_a": 0.3,
                "cn_b": 0.48,
                "cn_c": 0.65,
                "cn_d": 0.73,
                "c_factor": 0.014,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 52,
                "lu_name": "Scrub/Shrub",
                "cn_a": 0.3,
                "cn_b": 0.48,
                "cn_c": 0.65,
                "cn_d": 0.73,
                "c_factor": 0.014,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0,
            },
            {
                "lu_value": 71,
                "lu_name": "Grassland",
                "cn_a": 0.3,
                "cn_b": 0.58,
                "cn_c": 0.71,
                "cn_d": 0.78,
                "c_factor": 0.12,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.48,
                "tss": 55.3,
                "zinc": 0.03,
            },
            {
                "lu_value": 72,
                "lu_name": "Sedge Herbaceous",
                "cn_a": 0.3,
                "cn_b": 0.58,
                "cn_c": 0.71,
                "cn_d": 0.78,
                "c_factor": 0.12,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 74,
                "lu_name": "Moss",
                "cn_a": 0.3,
                "cn_b": 0.58,
                "cn_c": 0.71,
                "cn_d": 0.78,
                "c_factor": 0.12,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 81,
                "lu_name": "Pasture/Hay",
                "cn_a": 0.39,
                "cn_b": 0.61,
                "cn_c": 0.74,
                "cn_d": 0.8,
                "c_factor": 0.05,
                "lead": 0.03,
                "nitrogen": 2.48,
                "phosphorus": 0.42,
                "tss": 55.3,
                "zinc": 0.03,
            },
            {
                "lu_value": 82,
                "lu_name": "Cultivated Land",
                "cn_a": 0.67,
                "cn_b": 0.78,
                "cn_c": 0.85,
                "cn_d": 0.89,
                "c_factor": 0.24,
                "lead": 0.05,
                "nitrogen": 2.68,
                "phosphorus": 0.42,
                "tss": 55.3,
                "zinc": 0.03,
            },
            {
                "lu_value": 90,
                "lu_name": "Woody Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 95,
                "lu_name": "Emergent Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
        ]

    def ccap_properties(self):
        return [
            {
                "lu_value": 0,
                "lu_name": "Background",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 1,
                "lu_name": "No Data",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 2,
                "lu_name": "High Intensity Developed",
                "cn_a": 0.89,
                "cn_b": 0.92,
                "cn_c": 0.94,
                "cn_d": 0.95,
                "c_factor": 0,
                "lead": 0.09,
                "nitrogen": 2.22,
                "phosphorus": 0.47,
                "tss": 71,
                "zinc": 0.06,
            },
            {
                "lu_value": 3,
                "lu_name": "Medium Intensity Developed",
                "cn_a": 0.77,
                "cn_b": 0.85,
                "cn_c": 0.9,
                "cn_d": 0.92,
                "c_factor": 0.01,
                "lead": 0.06,
                "nitrogen": 2.29,
                "phosphorus": 0.3,
                "tss": 27,
                "zinc": 0.06,
            },
            {
                "lu_value": 4,
                "lu_name": "Low Intensity Developed",
                "cn_a": 0.61,
                "cn_b": 0.75,
                "cn_c": 0.83,
                "cn_d": 0.87,
                "c_factor": 0.03,
                "lead": 0.04,
                "nitrogen": 1.77,
                "phosphorus": 0.18,
                "tss": 19.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 5,
                "lu_name": "Developed Open Space",
                "cn_a": 0.49,
                "cn_b": 0.69,
                "cn_c": 0.79,
                "cn_d": 0.84,
                "c_factor": 0.005,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 6,
                "lu_name": "Cultivated Land",
                "cn_a": 0.67,
                "cn_b": 0.78,
                "cn_c": 0.85,
                "cn_d": 0.89,
                "c_factor": 0.24,
                "lead": 0.03,
                "nitrogen": 2.68,
                "phosphorus": 0.42,
                "tss": 107,
                "zinc": 0.03,
            },
            {
                "lu_value": 7,
                "lu_name": "Pasture/Hay",
                "cn_a": 0.39,
                "cn_b": 0.61,
                "cn_c": 0.74,
                "cn_d": 0.8,
                "c_factor": 0.05,
                "lead": 0.02,
                "nitrogen": 2.48,
                "phosphorus": 0.48,
                "tss": 55.3,
                "zinc": 0.03,
            },
            {
                "lu_value": 8,
                "lu_name": "Grassland",
                "cn_a": 0.3,
                "cn_b": 0.58,
                "cn_c": 0.71,
                "cn_d": 0.78,
                "c_factor": 0.12,
                "lead": 0.03,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 55.3,
                "zinc": 0.03,
            },
            {
                "lu_value": 9,
                "lu_name": "Deciduous Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.009,
                "lead": 0,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 10,
                "lu_name": "Evergreen Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.004,
                "lead": 0,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 11,
                "lu_name": "Mixed Forest",
                "cn_a": 0.3,
                "cn_b": 0.55,
                "cn_c": 0.7,
                "cn_d": 0.77,
                "c_factor": 0.007,
                "lead": 0,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 12,
                "lu_name": "Scrub/Shrub",
                "cn_a": 0.3,
                "cn_b": 0.48,
                "cn_c": 0.65,
                "cn_d": 0.73,
                "c_factor": 0.014,
                "lead": 0,
                "nitrogen": 1.25,
                "phosphorus": 0.05,
                "tss": 11.1,
                "zinc": 0.03,
            },
            {
                "lu_value": 13,
                "lu_name": "Palustrine Forested Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0.003,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 14,
                "lu_name": "Palustrine Scrub/Shrub Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 15,
                "lu_name": "Palustrine Emergent Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 16,
                "lu_name": "Estuarine Forested Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0.003,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 17,
                "lu_name": "Estuarine Scrub/Shrub Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0.003,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 18,
                "lu_name": "Estuarine Emergent Wetland",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0.003,
                "lead": 0,
                "nitrogen": 1.1,
                "phosphorus": 0.2,
                "tss": 19,
                "zinc": 0,
            },
            {
                "lu_value": 19,
                "lu_name": "Unconsolidated Shore",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0.5,
                "lead": 0.03,
                "nitrogen": 0.97,
                "phosphorus": 0.12,
                "tss": 70,
                "zinc": 0.03,
            },
            {
                "lu_value": 20,
                "lu_name": "Bare Land",
                "cn_a": 0.77,
                "cn_b": 0.86,
                "cn_c": 0.91,
                "cn_d": 0.94,
                "c_factor": 0.7,
                "lead": 0.03,
                "nitrogen": 0.97,
                "phosphorus": 0.12,
                "tss": 70,
                "zinc": 0.03,
            },
            {
                "lu_value": 21,
                "lu_name": "Water",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 22,
                "lu_name": "Palustrine Aquatic Bed",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 23,
                "lu_name": "Estuarine Aquatic Bed",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 24,
                "lu_name": "Tundra",
                "cn_a": 0.3,
                "cn_b": 0.48,
                "cn_c": 0.65,
                "cn_d": 0.73,
                "c_factor": 0.014,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
            {
                "lu_value": 25,
                "lu_name": "Snow/Ice",
                "cn_a": 0,
                "cn_b": 0,
                "cn_c": 0,
                "cn_d": 0,
                "c_factor": 0,
                "lead": 0,
                "nitrogen": 0,
                "phosphorus": 0,
                "tss": 0,
                "zinc": 0,
            },
        ]
